In [1]:
# Load the diabetes dataset

from sklearn import tree
from pandas import read_csv
import os
import numpy as np
df = read_csv("sales_data_sample.csv")



In [2]:
# Separate the target variable (Outcome) from the features
x = np.array(df.drop(["SALES"], 1))
y = np.array(df["SALES"])

C:\Users\Welcome\AppData\Local\Temp\ipykernel_7376\2423101873.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(df.drop(["SALES"], 1))


In [4]:
y

array([2871.  , 2765.9 , 3884.34, ..., 5417.57, 2116.16, 3079.44])

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

In [47]:
from sklearn.linear_model import LinearRegression
# Create a linear regression model
model = LinearRegression()

In [48]:
# Fit the model to the training data
model.fit(x_train, y_train)

LinearRegression()

In [63]:
# Make predictions on the test data
y_pred = model.predict(x_test)

In [64]:
y_pred

array([ 3896.11188423,  4865.72398822,  2036.10234876,  5602.31660071,
        5659.9645893 ,  1366.85091607,  4675.19839872,   637.86169134,
        5066.22489846,  5032.86301898,  -248.71632998,  3750.33564842,
        5592.81632379,  3853.8646849 ,  2662.50210579,   790.56087562,
        3198.43736236,  4419.23620025,  1010.98408343,  1479.60831431,
        2936.39436639,  3070.93626481,  1577.47436156,  2021.68897217,
        4789.48872094,    86.10306926,  4153.50340049,  3475.16510439,
        -287.33010716,  4265.24719657,  4115.09910239,  1295.1185119 ,
        3110.70586764,  2388.62297884,  4798.10344424,  2126.84588858,
        5420.67813405,  5008.40601384,  4121.11595135,  2107.48389376,
        2905.40432606,  4633.6494683 ,  4742.88551919,  2780.8950813 ,
        3580.80606674,  2635.80585251,  3870.79084177,  4165.60258177,
        2889.28381267,  1982.11139484,  4305.76183646,   449.72845884,
        2720.5004246 ,  2453.53612343,  5703.12224507,  2838.27631402,
      

In [60]:
# to test the sanmple data
import numpy as np
test=np.array([3,7,2003,10134,41,94.74,2])
reshaped_test = test.reshape(1, -1)
reshaped_test
y_pred = model.predict(reshaped_test)

In [61]:
y_pred

array([4878.09917784])

In [66]:
(-22.52453303*3)+(7.02788889 *7)+(-36.16766958*2003)+(0.38153327*10134)+(105.13172685*41)+(60.38264346*94.74)+(-15.22005571*2)

-58595.15005658959

In [70]:
# Get the intercept and coefficients
intercept = model.intercept_
coefficients = model.coef_
print("intercept",intercept)
print("coefficients",coefficients)

intercept 63473.249190100796
coefficients [-22.52453303   7.02788889 -36.16766958   0.38153327 105.13172685
  60.38264346 -15.22005571]


In [69]:
intercept

63473.249190100796

In [73]:
# Y= a+bX
# a - intercept, b - coefficient

y=-58595.15005658959+63473.249190100796
print(y)


4878.099133511205
